### ISSUE TITLE
Latest 0.2.0 not starting correctly

### ISSUE THREAD

**Issue by DavidFW1960** [hassio-addons/app-appdaemon#10]
# Problem/Motivation

> updated to latest but it does not run

## Expected behavior

> expected addon to run

## Actual behavior

> receive errors in log constantly as it tries to start after an error
```
2020-02-24 10:22:05.673472 INFO AppDaemon: AppDaemon Version 4.0.1 starting
2020-02-24 10:22:05.673740 INFO AppDaemon: Python version is 3.8.1
2020-02-24 10:22:05.673898 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2020-02-24 10:22:05.674063 INFO AppDaemon: Added log: AppDaemon
2020-02-24 10:22:05.674238 INFO AppDaemon: Added log: Error
2020-02-24 10:22:05.674438 INFO AppDaemon: Added log: Access
2020-02-24 10:22:05.674602 INFO AppDaemon: Added log: Diag
2020-02-24 10:22:05.692897 WARNING AppDaemon: ------------------------------------------------------------
2020-02-24 10:22:05.693119 WARNING AppDaemon: Unexpected error during run()
2020-02-24 10:22:05.693283 WARNING AppDaemon: ------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/__main__.py", line 117, in run
    self.AD = ad.AppDaemon(self.logging, loop, **appdaemon)
  File "/usr/lib/python3.8/site-packages/appdaemon/appdaemon.py", line 188, in __init__
    self.sched = scheduler.Scheduler(self)
  File "/usr/lib/python3.8/site-packages/appdaemon/scheduler.py", line 54, in __init__
    self.init_sun()
  File "/usr/lib/python3.8/site-packages/appdaemon/scheduler.py", line 187, in init_sun
    self.location = astral.Location((
AttributeError: module 'astral' has no attribute 'Location'
2020-02-24 10:22:05.695393 INFO AppDaemon: Previous message repeated 1 times
2020-02-24 10:22:05.695532 INFO AppDaemon: AppDaemon Exited
[10:22:05] INFO: Starting AppDaemon...
```
Keeps repeating that error
I have only the defaults set in the addon
## Steps to reproduce

>update to 0.2.0

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by bratanon** [comment]
Issue confirmed, I have the same issue with 0.2.0.

**Comment by samnewman86** [comment]
Same here. astral.Location attribute error.
Any way to downgrade

**Comment by frenck** [comment]
Yeo, see the issue happening with the final release as well. Looking into it right away.

@samnewman86 Only way to downgrade is using Snapshots.

**Comment by bratanon** [comment]
@frenck I came across this thread that might help.
https://github.com/home-assistant/home-assistant/issues/31793#issuecomment-585876537

**Comment by frenck** [comment]
Yes, I'm familiar with the issue @bratanon. Thanks.

**Comment by rccoleman** [comment]
I just ran across this and it's relatively easy to fix for now.  Just specify the following in the addon config:

```
python_packages:
  - astral==1.10.1
```

**Comment by frenck** [comment]
Yeah, that will workaround it. However, the problem is here:

<https://github.com/home-assistant/appdaemon/blob/dev/requirements.txt#L1>

It is already pinned, however, the add-on is running 2.1 of astral, which makes no sense. So I'm trying to figure out why this happens.

<blockquote><img src="https://avatars1.githubusercontent.com/u/13844975?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/home-assistant/appdaemon">home-assistant/appdaemon</a></strong></div><div>:page_facing_up: Python Apps for Home Automation. Contribute to home-assistant/appdaemon development by creating an account on GitHub.</div></blockquote>

**Comment by rccoleman** [comment]
Isn't this it?  They're saying that the version wasn't pinned.

https://community.home-assistant.io/t/appdaemon-inactive-dead/171636/5

**Comment by frenck** [comment]
Oh right, it isn't pinned by AppDaemon in the current stable release, that is an issue indeed. Will pin it from the add-on end and push out a hotfix release right away.

**Comment by DavidFW1960** [comment]
Thanks @frenck for getting on it so quickly

**Comment by frenck** [comment]
No problem!

Add-on version v0.2.1 is published in the add-on store and addresses this issue.
If you don't see the update yet: Go to the add-on store, and click the refresh icon in the top right.

Sorry for the inconvenience this might have caused.

../Frenck

**Comment by samnewman86** [comment]
I wish i'd had been a bit more patient last night. 
I tried to restore a snapshot but it failed and completley messed up everything.
I was up to 3am trying to get the lights to work as we have guests staying and most are automated.
Need coffee...
