### ISSUE TITLE
WebUI error

### ISSUE THREAD

**Issue by Salvora** [hassio-addons/app-appdaemon#112]
# Problem/Motivation

WebUI won't open out of the box. My home assistant uses SSL but apparently this addon ignores the ssl settings of HA.
I can only access the dashboard with going to http://home_assistant_ip:5050

## Expected behavior

It should open with no problem like any other addon.

## Actual behavior

404

## Steps to reproduce

Set SSL on your HA instance.
Install addon
Try to open webui from supervisor/addons

Error:
```
Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
```

## Proposed changes

Some type of fix?

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
I believe Appdaemon has its own configuration for SSL, I would suggest looking at their docs.

https://appdaemon.readthedocs.io/en/latest/

#54
