### ISSUE TITLE
Pycurl build fails

### ISSUE THREAD

**Issue by underko** [hassio-addons/app-appdaemon#159]
# Problem/Motivation

I am unable to build and install pycurl. The build fails with `ModuleNotFoundError: No module named 'wheel.bdist_wheel'`. Could you please help me understand what am I doing wrong? This is after an update to the latest 0.7.0 version from previous version where the configuration worked ok.

Thank you in advance for any kind of help!

## Expected behavior

Pycurl succeeds to build an install.

## Actual behavior

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: AppDaemon 4
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.7.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.4  (amd64 / qemux86-64)
 Home Assistant Core: 2021.9.7
 Home Assistant Supervisor: 2021.09.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] appdaemon.sh: executing... 
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
v3.14.2-61-gbea5d59ab6 [https://dl-cdn.alpinelinux.org/alpine/v3.14/main]
v3.14.2-58-gdbf551a5fb [https://dl-cdn.alpinelinux.org/alpine/v3.14/community]
OK: 14943 distinct packages available
OK: 87 MiB in 64 packages
OK: 87 MiB in 64 packages
(1/9) Upgrading libcrypto1.1 (1.1.1k-r0 -> 1.1.1l-r0)
(2/9) Upgrading libssl1.1 (1.1.1k-r0 -> 1.1.1l-r0)
(3/9) Upgrading libcurl (7.78.0-r0 -> 7.79.1-r0)
(4/9) Installing pkgconf (1.7.4-r0)
(5/9) Installing openssl-dev (1.1.1l-r0)
(6/9) Installing nghttp2-dev (1.43.0-r0)
(7/9) Installing zlib-dev (1.2.11-r3)
(8/9) Installing brotli-dev (1.0.9-r5)
(9/9) Installing curl-dev (7.79.1-r0)
Executing busybox-1.33.1-r3.trigger
Executing ca-certificates-20191127-r5.trigger
OK: 89 MiB in 70 packages
Looking in links: https://wheels.home-assistant.io/alpine-3.13/amd64/
Collecting pycurl
  Downloading pycurl-7.44.1.tar.gz (227 kB)
Building wheels for collected packages: pycurl
  Building wheel for pycurl (setup.py): started
  Building wheel for pycurl (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tvl3x2py/pycurl_0bfccca8f5fb4f8192b46eff4813e3fb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tvl3x2py/pycurl_0bfccca8f5fb4f8192b46eff4813e3fb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-skhp8tm7
       cwd: /tmp/pip-install-tvl3x2py/pycurl_0bfccca8f5fb4f8192b46eff4813e3fb/
  Complete output (23 lines):
  Using curl-config (libcurl 7.79.1)
  Using SSL library: OpenSSL/LibreSSL/BoringSSL
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-tvl3x2py/pycurl_0bfccca8f5fb4f8192b46eff4813e3fb/setup.py", line 1003, in <module>
      setup(**setup_args)
    File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.9/distutils/core.py", line 134, in setup
      ok = dist.parse_command_line()
    File "/usr/lib/python3.9/distutils/dist.py", line 483, in parse_command_line
      args = self._parse_command_opts(parser, args)
    File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 916, in _parse_command_opts
      nargs = _Distribution._parse_command_opts(self, parser, args)
    File "/usr/lib/python3.9/distutils/dist.py", line 539, in _parse_command_opts
      cmd_class = self.get_command_class(command)
    File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 755, in get_command_class
      self.cmdclass[command] = cmdclass = ep.load()
    File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2450, in load
      return self.resolve()
    File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2456, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
  ModuleNotFoundError: No module named 'wheel.bdist_wheel'
  ----------------------------------------
  Running setup.py clean for pycurl
  ERROR: Failed building wheel for pycurl
Failed to build pycurl
Installing collected packages: pycurl
    Running setup.py install for pycurl: started
    Running setup.py install for pycurl: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tvl3x2py/pycurl_0bfccca8f5fb4f8192b46eff4813e3fb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tvl3x2py/pycurl_0bfccca8f5fb4f8192b46eff4813e3fb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-fe5xxd0z/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/pycurl
         cwd: /tmp/pip-install-tvl3x2py/pycurl_0bfccca8f5fb4f8192b46eff4813e3fb/
    Complete output (15 lines):
    Using curl-config (libcurl 7.79.1)
    Using SSL library: OpenSSL/LibreSSL/BoringSSL
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/curl
    copying python/curl/__init__.py -> build/lib.linux-x86_64-3.9/curl
    running build_ext
    building 'pycurl' extension
    creating build/temp.linux-x86_64-3.9
    creating build/temp.linux-x86_64-3.9/src
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPYCURL_VERSION="7.44.1" -DHAVE_CURL_SSL=1 -DHAVE_CURL_OPENSSL=1 -DHAVE_CURL_SSL=1 -I/usr/include/python3.9 -c src/docstrings.c -o build/temp.linux-x86_64-3.9/src/docstrings.o
    error: command 'gcc' failed: No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tvl3x2py/pycurl_0bfccca8f5fb4f8192b46eff4813e3fb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tvl3x2py/pycurl_0bfccca8f5fb4f8192b46eff4813e3fb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-fe5xxd0z/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.9/pycurl Check the logs for full command output.
[23:30:19] FATAL: Failed installing package pycurl
[cont-init.d] appdaemon.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

## Steps to reproduce

Start addon with following configuration:
```
system_packages:
  - libcrypto1.1
  - libssl1.1
  - curl-dev
python_packages:
  - pycurl
init_commands: []
```

**Comment by frenck** [comment]
If you install `curl-dev`, be sure to also install `curl`.

**Comment by underko** [comment]
Hello, sorry, but does it require some specific order? I've tried multiple variations of system_packages for example: 
```
system_packages:
  - libcrypto1.1
  - libssl1.1
  - curl
  - curl-dev
python_packages:
  - pycurl
init_commands: []
```

but am getting the same error.

**Comment by frenck** [comment]
`error: command 'gcc' failed: No such file or directory`

**Comment by underko** [comment]
Even using gcc and other packages that i normally use:
```
system_packages:
  - gcc
  - libcrypto1.1
  - libssl1.1
  - curl
  - curl-dev
  - musl
  - musl-dev
  - python3
  - python3-dev
  - libxml2-dev
  - libxslt-dev
  - linux-headers
python_packages:
  - pycurl
  - lxml
  - requests
  - influxdb
  - psutil
  - azure-cosmos
init_commands: []
```

Results in the following error while building pycurl:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: AppDaemon 4
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.7.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.4  (amd64 / qemux86-64)
 Home Assistant Core: 2021.9.7
 Home Assistant Supervisor: 2021.09.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] appdaemon.sh: executing... 
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
v3.14.2-61-gbea5d59ab6 [https://dl-cdn.alpinelinux.org/alpine/v3.14/main]
v3.14.2-58-gdbf551a5fb [https://dl-cdn.alpinelinux.org/alpine/v3.14/community]
OK: 14943 distinct packages available
(1/9) Installing binutils (2.35.2-r2)
(2/9) Installing libgomp (10.3.1_git20210424-r2)
(3/9) Installing libatomic (10.3.1_git20210424-r2)
(4/9) Installing libgphobos (10.3.1_git20210424-r2)
(5/9) Installing gmp (6.2.1-r0)
(6/9) Installing isl22 (0.22-r0)
(7/9) Installing mpfr4 (4.1.0-r0)
(8/9) Installing mpc1 (1.2.1-r0)
(9/9) Installing gcc (10.3.1_git20210424-r2)
Executing busybox-1.33.1-r3.trigger
OK: 196 MiB in 73 packages
OK: 196 MiB in 73 packages
OK: 196 MiB in 73 packages
OK: 196 MiB in 73 packages
(1/9) Upgrading libcrypto1.1 (1.1.1k-r0 -> 1.1.1l-r0)
(2/9) Upgrading libssl1.1 (1.1.1k-r0 -> 1.1.1l-r0)
(3/9) Upgrading libcurl (7.78.0-r0 -> 7.79.1-r0)
(4/9) Installing pkgconf (1.7.4-r0)
(5/9) Installing openssl-dev (1.1.1l-r0)
(6/9) Installing nghttp2-dev (1.43.0-r0)
(7/9) Installing zlib-dev (1.2.11-r3)
(8/9) Installing brotli-dev (1.0.9-r5)
(9/9) Installing curl-dev (7.79.1-r0)
Executing busybox-1.33.1-r3.trigger
Executing ca-certificates-20191127-r5.trigger
OK: 198 MiB in 79 packages
OK: 198 MiB in 79 packages
(1/1) Installing musl-dev (1.2.2-r3)
OK: 209 MiB in 80 packages
OK: 209 MiB in 80 packages
(1/1) Installing python3-dev (3.9.5-r1)
Executing busybox-1.33.1-r3.trigger
OK: 253 MiB in 81 packages
(1/3) Installing xz-dev (5.2.5-r0)
(2/3) Installing libxml2 (2.9.12-r1)
(3/3) Installing libxml2-dev (2.9.12-r1)
Executing busybox-1.33.1-r3.trigger
OK: 261 MiB in 84 packages
(1/4) Installing libgpg-error (1.42-r0)
(2/4) Installing libgcrypt (1.9.4-r0)
(3/4) Installing libxslt (1.1.34-r1)
(4/4) Installing libxslt-dev (1.1.34-r1)
Executing busybox-1.33.1-r3.trigger
OK: 264 MiB in 88 packages
(1/1) Installing linux-headers (5.10.41-r0)
OK: 271 MiB in 89 packages
Looking in links: https://wheels.home-assistant.io/alpine-3.13/amd64/
Collecting pycurl
  Downloading pycurl-7.44.1.tar.gz (227 kB)
Building wheels for collected packages: pycurl
  Building wheel for pycurl (setup.py): started
  Building wheel for pycurl (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-x8wanr3v/pycurl_a241b03d0d9a4f6b9efb8a72d8b997fc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-x8wanr3v/pycurl_a241b03d0d9a4f6b9efb8a72d8b997fc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ec34nsdw
       cwd: /tmp/pip-install-x8wanr3v/pycurl_a241b03d0d9a4f6b9efb8a72d8b997fc/
  Complete output (23 lines):
  Using curl-config (libcurl 7.79.1)
  Using SSL library: OpenSSL/LibreSSL/BoringSSL
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-x8wanr3v/pycurl_a241b03d0d9a4f6b9efb8a72d8b997fc/setup.py", line 1003, in <module>
      setup(**setup_args)
    File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.9/distutils/core.py", line 134, in setup
      ok = dist.parse_command_line()
    File "/usr/lib/python3.9/distutils/dist.py", line 483, in parse_command_line
      args = self._parse_command_opts(parser, args)
    File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 916, in _parse_command_opts
      nargs = _Distribution._parse_command_opts(self, parser, args)
    File "/usr/lib/python3.9/distutils/dist.py", line 539, in _parse_command_opts
      cmd_class = self.get_command_class(command)
    File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 755, in get_command_class
      self.cmdclass[command] = cmdclass = ep.load()
    File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2450, in load
      return self.resolve()
    File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2456, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
  ModuleNotFoundError: No module named 'wheel.bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for pycurl
  Running setup.py clean for pycurl
Failed to build pycurl
Installing collected packages: pycurl
    Running setup.py install for pycurl: started
    Running setup.py install for pycurl: finished with status 'done'
  DEPRECATION: pycurl was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Successfully installed pycurl-7.44.1
```

Not sure if this is an addon issue though.

**Comment by frenck** [comment]
`  ModuleNotFoundError: No module named 'wheel.bdist_wheel'

Seems like you are missing py3-wheel

**Comment by underko** [comment]
That was it, success, thank you!
