### ISSUE TITLE
After Home Assistant 0.106.1 update :WARNING AppDaemon: Unexpected error in scheduler loop

### ISSUE THREAD

**Issue by stovedoctor** [hassio-addons/app-appdaemon#17]
arch | armv7l
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.6
timezone | America/Los_Angeles
version | 0.106.2
virtualenv | false

File "/usr/lib/python3.8/site-packages/appdaemon/scheduler.py", line 335, in get_next_entries
    next_exec = datetime.datetime.now(pytz.utc).replace(year=3000)
ValueError: day is out of range for month
2020-02-28 21:00:30.618830 WARNING AppDaemon: ------------------------------------------------------------
2020-02-28 21:00:31.623037 WARNING AppDaemon: ------------------------------------------------------------
2020-02-28 21:00:31.624641 WARNING AppDaemon: Unexpected error in scheduler loop
2020-02-28 21:00:31.626382 WARNING AppDaemon: ------------------------------------------------------------
2020-02-28 21:00:31.628362 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/scheduler.py", line 421, in loop
    next_entries = self.get_next_entries()
  File "/usr/lib/python3.8/site-packages/appdaemon/scheduler.py", line 335, in get_next_entries
    next_exec = datetime.datetime.now(pytz.utc).replace(year=3000)
ValueError: day is out of range for month
2020-02-28 21:00:31.630765 WARNING AppDaemon: ------------------------------------------------------------
2020-02-28 21:00:32.636106 WARNING AppDaemon: ------------------------------------------------------------
2020-02-28 21:00:32.637700 WARNING AppDaemon: Unexpected error in scheduler loop
2020-02-28 21:00:32.639466 WARNING AppDaemon: ------------------------------------------------------------
2020-02-28 21:00:32.641585 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/scheduler.py", line 421, in loop
    next_entries = self.get_next_entries()
  File "/usr/lib/python3.8/site-packages/appdaemon/scheduler.py", line 335, in get_next_entries
    next_exec = datetime.datetime.now(pytz.utc).replace(year=3000)
ValueError: day is out of range for month
2020-02-28 21:00:32.643746 WARNING AppDaemon: ------------------------------------------------------------
2020-02-28 21:00:33.648049 WARNING AppDaemon: ------------------------------------------------------------
2020-02-28 21:00:33.649891 WARNING AppDaemon: Unexpected error in scheduler loop
2020-02-28 21:00:33.651533 WARNING AppDaemon: ------------------------------------------------------------
2020-02-28 21:00:33.653957 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/scheduler.py", line 421, in loop
    next_entries = self.get_next_entries()
  File "/usr/lib/python3.8/site-packages/appdaemon/scheduler.py", line 335, in get_next_entries
    next_exec = datetime.datetime.now(pytz.utc).replace(year=3000)
ValueError: day is out of range for month
2020-02-28 21:00:33.655256 WARNING AppDaemon: ------------------------------------------------------------

**Comment by stovedoctor** [comment]
21:21:15.513139 WARNING AppDaemon: ------------------------------------------------------------'}, 'namespace': 'admin'},), 'kwargs': {}}
2020-02-28 21:21:15.527080 DEBUG AppDaemon: thread_async loop, args={'function': <bound method ADStream.send_update of <appdaemon.stream.ADStream object at 0xb5926be0>>, 'args': ({'event_type': '__AD_LOG_EVENT', 'data': {'level': 'WARNING', 'app_name': 'AppDaemon', 'message': 'Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/appdaemon/scheduler.py", line 421, in loop\n    next_entries = self.get_next_entries()\n  File "/usr/lib/python3.8/site-packages/appdaemon/scheduler.py", line 335, in get_next_entries\n    next_exec = datetime.datetime.now(pytz.utc).replace(year=3000)\nValueError: day is out of range for month\n', 'type': 'log', 'log_type': 'main_log', 'asctime': '2020-02-28 21:21:15.513985', 'formatted_message': '2020-02-28 21:21:15.513985 WARNING AppDaemon: Traceback (most recent call last):\n  File "/usr/lib/python3.8/site-packages/appdaemon/scheduler.py", line 421, in loop\n    next_entries = self.get_next_entries()\n  File "/usr/lib/python3.8/site-packages/appdaemon/scheduler.py", line 335, in get_next_entries\n    next_exec = datetime.datetime.now(pytz.utc).replace(year=3000)\nValueError: day is out of range for month\n'}, 'namespace': 'admin'},), 'kwargs': {}}
2020-02-28 21:21:15.527605 DEBUG AppDaemon: thread_async loop, args={'function': <bound method ADStream.send_update of <appdaemon.stream.ADStream object at 0xb5926be0>>, 'args': ({'event_type': '__AD_LOG_EVENT', 'data': {'level': 'WARNING', 'app_name': 'AppDaemon', 'message': '------------------------------------------------------------', 'type': 'log', 'log_type': 'main_log', 'asctime': '2020-02-28 21:21:15.514554', 'formatted_message': '2020-02-28 21:21:15.514554 WARNING AppDaemon: ------------------------------------------------------------'}, 'namespace': 'admin'},), 'kwargs': {}}
2020-02-28 21:21:15.533539 DEBUG AppDaemon: get_state: thread.thread-0.None None True
2020-02-28 21:21:15.533949 DEBUG AppDaemon: get_state: thread.thread-1.None None True
2020-02-28 21:21:15.534415 DEBUG HASS: Utility
2020-02-28 21:21:15.534863 DEBUG AppDaemon: set_state(): sensor.appdaemon_uptime, {'state': '0:01:09'}
2020-02-28 21:21:15.535301 DEBUG AppDaemon: parse_state: sensor.appdaemon_uptime, {'state': '0:01:09'}
2020-02-28 21:21:15.535830 DEBUG AppDaemon: Old state: {'state': '0:01:08', 'last_changed': '2020-02-28T21:21:14-08:00', 'attributes': {}}
2020-02-28 21:21:15.536188 DEBUG AppDaemon: New state: {'state': '0:01:09', 'last_changed': '2020-02-28T21:21:15-08:00', 'attributes': {}}
2020-02-28 21:21:15.536553 DEBUG AppDaemon: sending event locally
2020-02-28 21:21:15.536941 DEBUG AppDaemon: Event type:state_changed:
2020-02-28 21:21:15.537318 DEBUG AppDaemon: {'entity_id': 'sensor.appdaemon_uptime', 'new_state': {'state': '0:01:09', 'last_changed': '2020-02-28T21:21:15-08:00', 'attributes': {}}, 'old_state': {'state': '0:01:08', 'last_changed': '2020-02-28T21:21:14-08:00', 'attributes': {}}}
2020-02-28 21:21:15.537719 DEBUG AppDaemon: process_event_callbacks() admin {'event_type': 'state_changed', 'data': {'entity_id': 'sensor.appdaemon_uptime', 'new_state': {'state': '0:01:09', 'last_changed': '2020-02-28T21:21:15-08:00', 'attributes': {}}, 'old_state': {'state': '0:01:08', 'last_changed': '2020-02-28T21:21:14-08:00', 'attributes': {}}}}
2020-02-28 21:21:15.538391 DEBUG AppDaemon: Util loop compute time: 13.0ms, check_config()=8.0ms, other=5.0ms
2020-02-28 21:21:15.538992 DEBUG AppDaemon: thread_async loop, args={'function': <bound method ADStream.send_update of <appdaemon.stream.ADStream object at 0xb5926be0>>, 'args': ({'event_type': 'state_changed', 'data': {'entity_id': 'sensor.appdaemon_uptime', 'new_state': {'state': '0:01:09', 'last_changed': '2020-02-28T21:21:15-08:00', 'attributes': {}}, 'old_state': {'state': '0:01:08', 'last_changed': '2020-02-28T21:21:14-08:00', 'attributes': {}}}, 'namespace': 'admin'},), 'kwargs': {}}

**Comment by adandl** [comment]
Hello - I have the same issue in 0.106.2 with a blank AppDaemon 4 installation.
this message repeates over and over again:
```
2020-02-29 09:26:57.577074 WARNING AppDaemon: ------------------------------------------------------------
2020-02-29 09:26:57.575977 WARNING AppDaemon: Unexpected error in scheduler loop
2020-02-29 09:26:57.574775 WARNING AppDaemon: ------------------------------------------------------------
2020-02-29 09:26:56.570635 WARNING AppDaemon: ------------------------------------------------------------
2020-02-29 09:26:56.569528 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/scheduler.py", line 421, in loop
    next_entries = self.get_next_entries()
  File "/usr/lib/python3.8/site-packages/appdaemon/scheduler.py", line 335, in get_next_entries
    next_exec = datetime.datetime.now(pytz.utc).replace(year=3000)
ValueError: day is out of range for month
```

**Comment by samnewman86** [comment]
Hi the issue is because it's a special leap year and appdaemon doesnt handle it well.
It's been fixed but needs this add-on to be updated to include the latest version of appdaemon

**Comment by insajd** [comment]
Quickfix in the meantime https://github.com/home-assistant/appdaemon/issues/897#issuecomment-592919565

**Comment by frenck** [comment]
This is an ApppDaemon issue, not an add-on problem.
