### ISSUE TITLE
AppDaemon 0.9.2, HAOS 8.4, HAS 2022.07.0 fails to load for me now

### ISSUE THREAD

**Issue by bentwookie** [hassio-addons/app-appdaemon#206]
# Problem/Motivation

Hi. I let HA update to 8.4/2022.7.7/AppDaemon 0.9.2 and right after AppDaemon stopped servicing its webpage.

Version info:
Home Assistant 2022.7.7
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220707.1 - latest

## Expected behavior

Hoping that it can run as it did before (which was great! thanks for all the work on it!)

## Actual behavior

Here's the add-on log:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: AppDaemon
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.9.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.4  (amd64 / qemux86-64)
 Home Assistant Core: 2022.7.7
 Home Assistant Supervisor: 2022.07.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/appdaemon.sh
cont-init: info: /etc/cont-init.d/appdaemon.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun appdaemon (no readiness notification)
[11:35:18] INFO: Starting AppDaemon...
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 5, in <module>
    from appdaemon.__main__ import main
  File "/usr/lib/python3.10/site-packages/appdaemon/__main__.py", line 11, in <module>
    import asyncio
  File "/usr/lib/python3.10/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/lib/python3.10/asyncio/base_events.py", line 25, in <module>
    import subprocess
ValueError: source code string cannot contain null bytes
[11:35:18] WARNING: AppDaemon crashed, halting add-on
s6-rc: info: service legacy-services successfully started
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

```## Steps to reproduce

I didn't try to backrev and see if I could reproduce it. Restarting the add-on didn't fix it.

**Comment by bentwookie** [comment]
Uninstalling the add-on and then reinstalling it fixed the problem.

**Comment by frenck** [comment]
Good to hear you got if fixed 👍
