### ISSUE TITLE
Since 0.12.0 app won't load anymore

### ISSUE THREAD

**Issue by sweetpants** [hassio-addons/app-appdaemon#248]
# Problem/Motivation

> Since upgrade to version 0.12.0 today one of my appdaemon apps won't load anymore

## Expected behavior

> Should load just like before

## Actual behavior

> Won;t load + error in error.log

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

Error log says:
2023-04-11 15:40:49.869896 WARNING Error: ------------------------------------------------------------
2023-04-11 18:34:58.789685 WARNING Error: ------------------------------------------------------------
2023-04-11 18:34:58.790647 WARNING Error: Unexpected error loading module: /config/appdaemon/apps/AlarmSystem/alarm_system.py:
2023-04-11 18:34:58.791271 WARNING Error: ------------------------------------------------------------
2023-04-11 18:34:58.795186 WARNING Error: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 999, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.10/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 782, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/appdaemon/apps/AlarmSystem/alarm_system.py", line 3, in <module>
    import voluptuous as vol
ModuleNotFoundError: No module named 'voluptuous'

2023-04-11 18:34:58.795799 WARNING Error: ------------------------------------------------------------

appdaemon.log says:

2023-04-11 18:34:56.652267 INFO AppDaemon: App 'hall_door' added
2023-04-11 18:34:56.656830 INFO AppDaemon: App 'upstairs_motion' added
2023-04-11 18:34:56.659122 INFO AppDaemon: App 'central_heating' added
2023-04-11 18:34:56.661214 INFO AppDaemon: App 'alarm_system' added
2023-04-11 18:34:56.662974 INFO AppDaemon: Found 4 active apps
2023-04-11 18:34:56.663776 INFO AppDaemon: Found 0 inactive apps
2023-04-11 18:34:56.664488 INFO AppDaemon: Found 0 global libraries
2023-04-11 18:34:56.665298 INFO AppDaemon: Starting Apps with 4 workers and 4 pins
2023-04-11 18:34:56.669014 INFO AppDaemon: Running on port 5050
2023-04-11 18:34:56.740553 INFO HASS: Evaluating startup conditions
2023-04-11 18:34:56.757083 INFO HASS: Startup condition met: hass state=RUNNING
2023-04-11 18:34:56.757883 INFO HASS: All startup conditions met
2023-04-11 18:34:56.824671 INFO AppDaemon: Got initial state from namespace default
2023-04-11 18:34:58.682226 INFO AppDaemon: Scheduler running in realtime
2023-04-11 18:34:58.688045 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2023-04-11 18:34:58.689691 INFO AppDaemon: Adding /config/appdaemon/apps/AlarmSystem to module import path
2023-04-11 18:34:58.691104 INFO AppDaemon: Adding /config/appdaemon/apps/CentralHeating to module import path
2023-04-11 18:34:58.700157 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/change_detected.py
2023-04-11 18:34:58.780106 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/AlarmSystem/alarm_system.py
2023-04-11 18:34:58.796381 WARNING AppDaemon: Unexpected error loading module: /config/appdaemon/apps/AlarmSystem/alarm_system.py:
2023-04-11 18:34:58.796985 WARNING AppDaemon: Removing associated apps:
2023-04-11 18:34:58.797608 WARNING AppDaemon: alarm_system
2023-04-11 18:34:58.801312 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/CentralHeating/central_heating.py
2023-04-11 18:34:58.806663 INFO AppDaemon: Loading app hall_door using class ChangeDetected from module change_detected
2023-04-11 18:34:58.809827 INFO AppDaemon: Loading app upstairs_motion using class ChangeDetected from module change_detected
2023-04-11 18:34:58.813241 INFO AppDaemon: Loading app central_heating using class CentralHeating from module central_heating
2023-04-11 18:34:58.817758 INFO AppDaemon: Calling initialize() for hall_door
2023-04-11 18:34:58.823475 INFO AppDaemon: Calling initialize() for upstairs_motion
2023-04-11 18:34:58.829045 INFO AppDaemon: Calling initialize() for central_heating
2023-04-11 18:34:58.839610 INFO AppDaemon: App initialization complete

Now my alarm system does not work anymore

regards, Harry

**Comment by sweetpants** [comment]
Error was comming from my app itself, sorry for that
