### ISSUE TITLE
Appdaemon Starting fail loop

### ISSUE THREAD

**Issue by ggsleep776** [hassio-addons/app-appdaemon#255]
# Problem/Motivation

> Unable to start Appdaemon

Log

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: AppDaemon
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.12.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.1  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.4.6
 Home Assistant Supervisor: 2023.04.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[01:25:32] INFO: Starting AppDaemon...
2023-05-03 19:25:42.759454 INFO AppDaemon: AppDaemon Version 4.4.2 starting
2023-05-03 19:25:42.760987 INFO AppDaemon: Python version is 3.10.11
2023-05-03 19:25:42.762226 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2023-05-03 19:25:42.763285 INFO AppDaemon: Added log: AppDaemon
2023-05-03 19:25:42.764355 INFO AppDaemon: Added log: Error
2023-05-03 19:25:42.765285 INFO AppDaemon: Added log: Access
2023-05-03 19:25:42.766282 INFO AppDaemon: Added log: Diag
2023-05-03 19:25:43.276447 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2023-05-03 19:25:43.708868 INFO HASS: HASS Plugin Initializing
2023-05-03 19:25:43.709334 INFO HASS: HASS Plugin initialization complete
2023-05-03 19:25:43.709984 WARNING AppDaemon: ------------------------------------------------------------
2023-05-03 19:25:43.710421 WARNING AppDaemon: Unexpected error during run()
2023-05-03 19:25:43.710785 WARNING AppDaemon: ------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/__main__.py", line 131, in run
    self.AD = ad.AppDaemon(self.logging, loop, **appdaemon)
  File "/usr/lib/python3.10/site-packages/appdaemon/appdaemon.py", line 250, in __init__
    self.plugins = plugins.Plugins(self, args)
  File "/usr/lib/python3.10/site-packages/appdaemon/plugin_management.py", line 103, in __init__
    self.plugins[name]["refresh_delay"] = 600
TypeError: 'str' object does not support item assignment
2023-05-03 19:25:43.714877 INFO AppDaemon: Previous message repeated 1 times
2023-05-03 19:25:43.715212 INFO AppDaemon: AppDaemon Exited
[01:25:44] INFO: Service AppDaemon exited with code 0 (by signal 0)
[01:25:45] INFO: Starting AppDaemon...`
```

## Expected behavior

> Appdaemon should start

## Actual behavior

> Appdaemon start fail loop

## Steps to reproduce

> Uninstall Appdaemon
> Install Appdaemon via Addon Store
> Click Start

**Comment by ggsleep776** [comment]
It is fixed after updating to Home Assistant Core 2023.5.0
