### ISSUE TITLE
after update to latest version appdaemon not working - ERROR Error loading secrets file: /config/secrets.yaml

### ISSUE THREAD

**Issue by lpt2007** [hassio-addons/app-appdaemon#307]
PROBLEM:
After update to version 0.15.2 AppDaemon won't start. I lose all configuration data inside /config/appdaemon whitch I copied back from backup.

ERROR:
`Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 8, in <module>
    sys.exit(main())
ERROR Error loading secrets file: /config/secrets.yaml
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 417, in main
    admain.main()
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 276, in main
    if "appdaemon" not in config:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable`

**Comment by lpt2007** [comment]
Here is same thing:) Sorry
https://github.com/hassio-addons/addon-appdaemon/issues/287
