### ISSUE TITLE
Schedy App/script not working after update Appdaemon to 0.15.2

### ISSUE THREAD

**Issue by MarekLe** [hassio-addons/app-appdaemon#311]
# Problem/Motivation

After update Appdaemon to 0.15.2 Schedy App not working. There is error in Appdaemon's log.

## Expected behavior

Schedy app should working as usual.

## Actual behavior

This error appears in Appdaemon log:

```
2023-12-06 16:35:06.969918 WARNING schedy: ------------------------------------------------------------
2023-12-06 16:35:06.970282 WARNING schedy: Unexpected error initializing app: schedy:
2023-12-06 16:35:06.970469 WARNING schedy: ------------------------------------------------------------
2023-12-06 16:35:06.971475 WARNING schedy: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 1035, in check_app_updates
    await self.init_object(app)
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 338, in init_object
    "object": app_class(
              ^^^^^^^^^^
  File "/config/apps/hass_apps/loader.py", line 29, in _proxy_loader
    app_mod = _import_app_module(app_package)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/hass_apps/loader.py", line 24, in _import_app_module
    return importlib.import_module(mod_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/apps/hass_apps/schedy/app.py", line 14, in <module>
    from .. import common
  File "/config/apps/hass_apps/common.py", line 9, in <module>
    import voluptuous as vol
ModuleNotFoundError: No module named 'voluptuous'

2023-12-06 16:35:06.971687 WARNING schedy: ------------------------------------------------------------
```

## Steps to reproduce

Update Appdaemon to 0.15.2. Install Schedy app script.

## Proposed changes

Please repair this.

**Comment by frenck** [comment]
> ModuleNotFoundError: No module named 'voluptuous'

Seems like your app is missing a dependency?

**Comment by MarekLe** [comment]
> > ModuleNotFoundError: No module named 'voluptuous'
> 
> Seems like your app is missing a dependency?

Yes exactly. But 'Schedy' is not 'my' app. Its Appdaemon build in app. I tried to run Schedy on 'standalone' Appdaemon (in separate linux server - in python pip container). It looks like this 3 dependencies are needed:
pip install voluptuous
pip install observable
pip install cached_property

Schedy is my main heating controller. So it's a 'little' important to me ;-). Now it's -12C in Poland :-(.

**Comment by frenck** [comment]
Schedy is not a built-in app.

See also: <https://hass-apps.readthedocs.io/en/stable/getting-started.html#installation-in-hass-io>

**Comment by MarekLe** [comment]
Ok I see. But is it possible for Schedy to work again within addon-appdaemon?

**Comment by frenck** [comment]
I don't see why it wouldn't?

**Comment by MarekLe** [comment]
Problem persists after updating Appdaemon addon to 0.16.2.

**Comment by frenck** [comment]
> Problem persists after updating Appdaemon addon to 0.16.2.

Sure, this is not an add-on issue... so updating the add-on won't change that.
