### ISSUE TITLE
log error `UnicodeDecodeError`

### ISSUE THREAD

**Issue by Anto79-ops** [hassio-addons/app-appdaemon#350]
Hello,

Seeing this in AD addon (ver: 0.16.6)  logs on HAOS.

thanks

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

2024-09-18 10:43:05.065189 INFO MQTT: Unable to decode MQTT message
2024-09-18 10:43:05.065910 ERROR MQTT: Unable to decode MQTT message, with Traceback: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/plugins/mqtt/mqttplugin.py", line 271, in mqtt_on_message
    payload = payload.decode()
              ^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

2024-09-18 10:47:01.173652 INFO MQTT: Unable to decode MQTT message
2024-09-18 10:47:01.174345 ERROR MQTT: Unable to decode MQTT message, with Traceback: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/plugins/mqtt/mqttplugin.py", line 271, in mqtt_on_message
    payload = payload.decode()
              ^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

2024-09-18 10:50:53.357415 INFO MQTT: Unable to decode MQTT message
2024-09-18 10:50:53.358181 ERROR MQTT: Unable to decode MQTT message, with Traceback: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/plugins/mqtt/mqttplugin.py", line 271, in mqtt_on_message
    payload = payload.decode()
              ^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

2024-09-18 10:54:47.955705 INFO MQTT: Unable to decode MQTT message
2024-09-18 10:54:47.956193 ERROR MQTT: Unable to decode MQTT message, with Traceback: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/plugins/mqtt/mqttplugin.py", line 271, in mqtt_on_message
    payload = payload.decode()
              ^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

2024-09-18 10:55:04.333653 INFO MQTT: Unable to decode MQTT message
2024-09-18 10:55:04.334190 ERROR MQTT: Unable to decode MQTT message, with Traceback: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/plugins/mqtt/mqttplugin.py", line 271, in mqtt_on_message
    payload = payload.decode()
              ^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

2024-09-18 11:00:23.826721 INFO MQTT: Unable to decode MQTT message
2024-09-18 11:00:23.827232 ERROR MQTT: Unable to decode MQTT message, with Traceback: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/plugins/mqtt/mqttplugin.py", line 271, in mqtt_on_message
    payload = payload.decode()
              ^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

2024-09-18 11:01:04.448018 INFO MQTT: Unable to decode MQTT message
2024-09-18 11:01:04.448690 ERROR MQTT: Unable to decode MQTT message, with Traceback: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/plugins/mqtt/mqttplugin.py", line 271, in mqtt_on_message
    payload = payload.decode()
              ^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

2024-09-18 11:05:19.438034 INFO MQTT: Unable to decode MQTT message
2024-09-18 11:05:19.438766 ERROR MQTT: Unable to decode MQTT message, with Traceback: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/plugins/mqtt/mqttplugin.py", line 271, in mqtt_on_message
    payload = payload.decode()
              ^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

2024-09-18 11:09:17.908246 INFO MQTT: Unable to decode MQTT message
2024-09-18 11:09:17.908974 ERROR MQTT: Unable to decode MQTT message, with Traceback: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/plugins/mqtt/mqttplugin.py", line 271, in mqtt_on_message
    payload = payload.decode()
              ^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

**Comment by Anto79-ops** [comment]
Looks like this was solved on version 0.16.7. I haven't seen it in the logs almost 19 hours after update.

 Thank you

**Comment by anandv85** [comment]
Seeing this issue in version 0.16.7.  Several sensor status are being discarded at the receiving end due to this error.  Please kindly look into this issue and provide a solution.  Let me know if need a detailed error report. Thanks!
![image](https://github.com/user-attachments/assets/f612c1a8-20f9-410f-a64f-506108a279e0)
![image](https://github.com/user-attachments/assets/cde89751-170f-4aa3-b47c-f42373fbb611)

**Comment by anandv85** [comment]
> Looks like this was solved on version 0.16.7. I haven't seen it in the logs almost 19 hours after update.
> 
> Thank you

Could you please check again? I'm seeing this issue with 0.16.7 also.

Thanks,
Anand

**Comment by Anto79-ops** [comment]
I'm still not seeing it on my add-on but I'll reopen the issue for you

**Comment by Anto79-ops** [comment]
Just curious how quickly does it show up in the logs? Is it almost instant or does it take some time like days?

**Comment by anandv85** [comment]
> Just curious how quickly does it show up in the logs? Is it almost instant or does it take some time like days?

It is almost instant.  For every 5 seconds, I'm seeing this message.  Do you want to collect any additional information for debugging?

**Comment by anandv85** [comment]
> Just curious how quickly does it show up in the logs? Is it almost instant or does it take some time like days?

Basically, I'm trying to run the "Qolsys Gateway - qolsysgw" (installed through HACS) using the Appdaemon.  Most likely, the Qolsys Gateway is trying to send/receive a message through MQTT and then it throws those error messages.  I never worked on the Python sutff before so I don't know how to debug further.  Possibly, error decoding a message packet.  Please let me know if you want me to look at any specific lines of code or modify any of the Python script to get you more debugging messages.

**Comment by Anto79-ops** [comment]
sorry, im not a dev. I'm sure someone will see this and comment on the issue.

But, I'm using that exact integration (Qolsys Gateway), with AD and I haven't seen the error in the logs since upating to 0.16.7.

**Comment by Anto79-ops** [comment]
oh wait a second.... I see one log on 0.16.7

```
2024-09-27 06:35:35.571838 ERROR MQTT: Unable to decode MQTT message, with Traceback: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/plugins/mqtt/mqttplugin.py", line 271, in mqtt_on_message
    payload = payload.decode()
              ^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

Ok, thanks for bringing it up! 

Its still an issue.

**Comment by anandv85** [comment]
Thanks for re-opening the issue.  Mine is 0xff in position 0.  This is very consistent and I'm getting every 10 seconds or so.

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte`

**Comment by Anto79-ops** [comment]
intersting because mine used to log it every often (probably every 10 seconds), but now, this is the first one single log I've seen since the update. Maybe some sensor triggers it?

someone lese reportred at the QolsysGW repo:

https://github.com/XaF/qolsysgw/issues/163

**Comment by sinclairpaul** [comment]
The AppDaemon repo (which the addon installs) is at <https://github.com/AppDaemon/appdaemon>, I would suggest looking there.

**Comment by Anto79-ops** [comment]
thanks, opened an issue there.

https://github.com/AppDaemon/appdaemon/issues/2103

cheers
