### ISSUE TITLE
ImportError: Error loading shared library libxslt.so.1: No such file or directory

### ISSUE THREAD

**Issue by jeepotvin** [hassio-addons/app-appdaemon#49]
# Problem/Motivation
Hi! Just created my first Python script. :)
It works when I test it outside of AppDaemon, using tools such as Spyder (Anaconda3).
Although there seems to be a problem importing packages when starting the add-on.

## Expected behavior
I want the script not to crash on startup.
Running Home Assistant OS on RPi3.

## Actual behavior
When starting the addon, this is the output log.
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: AppDaemon 4
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.3.1
 You are running the latest version of this add-on.
 System: HassOS 4.13  (armv7 / raspberrypi3)
 Home Assistant Core: 0.116.0
 Home Assistant Supervisor: 247
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] appdaemon.sh: executing... 
Looking in links: https://wheels.home-assistant.io/alpine-3.12/armv7/
Collecting lxml
  Downloading https://wheels.home-assistant.io/alpine-3.12/armv7/lxml-4.5.2-cp38-none-any.whl (1.5 MB)
Installing collected packages: lxml
Successfully installed lxml-4.5.2
Looking in links: https://wheels.home-assistant.io/alpine-3.12/armv7/
Requirement already satisfied: requests in /usr/lib/python3.8/site-packages (2.23.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3.8/site-packages (from requests) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3.8/site-packages (from requests) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.8/site-packages (from requests) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.8/site-packages (from requests) (2020.4.5.1)
[cont-init.d] appdaemon.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:08:24] INFO: Starting AppDaemon...
2020-10-13 19:08:28.652263 INFO AppDaemon: AppDaemon Version 4.0.5 starting
2020-10-13 19:08:28.653227 INFO AppDaemon: Python version is 3.8.5
2020-10-13 19:08:28.654391 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2020-10-13 19:08:28.655314 INFO AppDaemon: Added log: AppDaemon
2020-10-13 19:08:28.656315 INFO AppDaemon: Added log: Error
2020-10-13 19:08:28.657114 INFO AppDaemon: Added log: Access
2020-10-13 19:08:28.658106 INFO AppDaemon: Added log: Diag
2020-10-13 19:08:28.761164 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2020-10-13 19:08:28.874907 INFO HASS: HASS Plugin Initializing
2020-10-13 19:08:28.876062 INFO HASS: HASS Plugin initialization complete
2020-10-13 19:08:28.878519 INFO AppDaemon: Initializing HTTP
2020-10-13 19:08:28.880432 INFO AppDaemon: Using 'ws' for event stream
2020-10-13 19:08:28.893297 INFO AppDaemon: Starting API
2020-10-13 19:08:28.910269 INFO AppDaemon: Starting Admin Interface
2020-10-13 19:08:28.912400 INFO AppDaemon: Starting Dashboards
2020-10-13 19:08:29.185167 INFO HASS: Connected to Home Assistant 0.116.0
2020-10-13 19:08:29.319869 INFO AppDaemon: App 'hello_world' added
2020-10-13 19:08:29.321558 INFO AppDaemon: App 'campus_occupancy' added
2020-10-13 19:08:29.324669 INFO AppDaemon: Found 2 total apps
2020-10-13 19:08:29.326564 INFO AppDaemon: Starting Apps with 2 workers and 2 pins
2020-10-13 19:08:29.330323 INFO AppDaemon: Running on port 5050
2020-10-13 19:08:29.709124 INFO HASS: Evaluating startup conditions
2020-10-13 19:08:29.787840 INFO HASS: Startup condition met: hass state=RUNNING
2020-10-13 19:08:29.789532 INFO HASS: All startup conditions met
2020-10-13 19:08:29.917559 INFO AppDaemon: Got initial state from namespace default
2020-10-13 19:08:31.369272 INFO AppDaemon: Scheduler running in realtime
2020-10-13 19:08:31.448387 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2020-10-13 19:08:31.456705 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/campus.py
2020-10-13 19:08:31.517798 WARNING Error: ------------------------------------------------------------
2020-10-13 19:08:31.519226 WARNING Error: Unexpected error loading module: /config/appdaemon/apps/campus.py:
2020-10-13 19:08:31.520475 WARNING Error: ------------------------------------------------------------
2020-10-13 19:08:34.432525 WARNING Error: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 875, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 290, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 668, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/appdaemon/apps/campus.py", line 7, in <module>
    from lxml import etree, html
ImportError: Error loading shared library libxslt.so.1: No such file or directory (needed by /usr/lib/python3.8/site-packages/lxml/etree.cpython-38-arm-linux-gnueabihf.so)
2020-10-13 19:08:34.434834 WARNING Error: ------------------------------------------------------------
2020-10-13 19:08:34.436827 WARNING AppDaemon: Removing associated apps:
2020-10-13 19:08:34.439077 WARNING AppDaemon: campus_occupancy
2020-10-13 19:08:34.451521 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/hello.py
2020-10-13 19:08:34.468729 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
2020-10-13 19:08:34.958138 INFO hello_world: Hello from AppDaemon
2020-10-13 19:08:34.967911 INFO hello_world: You are now ready to run Apps!
2020-10-13 19:08:34.978940 INFO AppDaemon: App initialization complete
```

## Steps to reproduce
This is the add-on configuration:
```
system_packages: []
python_packages:
  - lxml
  - requests
init_commands: []
```

The script has these lines included:
```
import appdaemon.plugins.hass.hassapi as hass
from lxml import etree, html
import re
import requests
import json
```

The Internet [points](https://github.com/kdmurray91/SRApy/issues/1#issuecomment-412655742) me in the direction of `sudo apt-get install libxslt-dev`. I've tried this through the console access found in the Portainer add-on with no luck. (sorry relatively new to docker)

Is there some other package I must include in the configuration? Or how do you suggest I import this `libxslt-dev` package?

Any help is appreciated. Thanks!

**Comment by sinclairpaul** [comment]
https://pkgs.alpinelinux.org/contents?file=libxslt.so.1&path=&name=&branch=v3.12

You should be able to add ```libxslt``` to system packages in the config

**Comment by jeepotvin** [comment]
Many thanks. Sorry it wasn't that obvious to me. It works now. Glad I asked. 💯
