### ISSUE TITLE
Wont open WEBUI

### ISSUE THREAD

**Issue by etmipamidzi** [hassio-addons/app-appdaemon#95]
Hi im new here so excuse me for maybe stupid questions. I have installed Appdaemon 4 on raspi homeassistant
 Add-on: AppDaemon 4
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.5.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.12  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2021.3.4
 Home Assistant Supervisor: 2021.03.6

Web ui wont start. I dont know wha exactly to setup after installation of addon. 
log is :
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] appdaemon.sh: executing... 
[cont-init.d] appdaemon.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:11:43] INFO: Starting AppDaemon...
2021-03-24 09:11:47.984109 INFO AppDaemon: AppDaemon Version 4.0.6 starting
2021-03-24 09:11:47.985244 INFO AppDaemon: Python version is 3.8.8
2021-03-24 09:11:47.986437 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2021-03-24 09:11:47.987622 INFO AppDaemon: Added log: AppDaemon
2021-03-24 09:11:47.988623 INFO AppDaemon: Added log: Error
2021-03-24 09:11:47.989473 INFO AppDaemon: Added log: Access
2021-03-24 09:11:47.990330 INFO AppDaemon: Added log: Diag
2021-03-24 09:11:48.131894 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2021-03-24 09:11:48.360720 INFO HASS: HASS Plugin Initializing
2021-03-24 09:11:48.362288 INFO HASS: HASS Plugin initialization complete
2021-03-24 09:11:48.364964 INFO AppDaemon: Initializing HTTP
2021-03-24 09:11:48.366864 INFO AppDaemon: Using 'ws' for event stream
2021-03-24 09:11:48.381828 INFO AppDaemon: Starting API
2021-03-24 09:11:48.398531 INFO AppDaemon: Starting Admin Interface
2021-03-24 09:11:48.400106 WARNING AppDaemon: ------------------------------------------------------------
2021-03-24 09:11:48.401497 WARNING AppDaemon: Unexpected error in HTTP module
2021-03-24 09:11:48.402793 WARNING AppDaemon: ------------------------------------------------------------
2021-03-24 09:11:48.420900 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/http.py", line 208, in __init__
    self.admin_obj = adadmin.Admin(
TypeError: type object argument after ** must be a mapping, not str
2021-03-24 09:11:48.423402 WARNING AppDaemon: ------------------------------------------------------------
2021-03-24 09:11:48.490118 INFO HASS: Connected to Home Assistant 2021.3.4
2021-03-24 09:11:48.546994 INFO AppDaemon: App 'hello_world' added
2021-03-24 09:11:48.551601 INFO AppDaemon: Found 1 total apps
2021-03-24 09:11:48.553990 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2021-03-24 09:11:48.557787 INFO AppDaemon: Running on port 5050
2021-03-24 09:11:48.698545 INFO HASS: Evaluating startup conditions
2021-03-24 09:11:48.740736 INFO HASS: Startup condition met: hass state=RUNNING
2021-03-24 09:11:48.742481 INFO HASS: All startup conditions met
2021-03-24 09:11:48.798649 INFO AppDaemon: Got initial state from namespace default
2021-03-24 09:11:50.588689 INFO AppDaemon: Scheduler running in realtime
2021-03-24 09:11:50.598637 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2021-03-24 09:11:50.605697 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/hello.py
2021-03-24 09:11:50.650312 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
2021-03-24 09:11:50.997228 INFO hello_world: Hello from AppDaemon
2021-03-24 09:11:51.003765 INFO hello_world: You are now ready to run Apps!
2021-03-24 09:11:51.009932 INFO AppDaemon: App initialization complete
Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.8/site-packages/appdaemon/http.py", line 61, in wrapper
    return await myfunc(*args)
  File "/usr/lib/python3.8/site-packages/appdaemon/http.py", line 976, in admin_page
    return await self._admin_page(request)
  File "/usr/lib/python3.8/site-packages/appdaemon/http.py", line 980, in _admin_page
    response = await self.admin_obj.admin_page(request.scheme, request.host)
AttributeError: 'NoneType' object has no attribute 'admin_page'

**Comment by frenck** [comment]
Unfortunately, this is an upstream issue:

```
2021-03-24 09:11:48.381828 INFO AppDaemon: Starting API
2021-03-24 09:11:48.398531 INFO AppDaemon: Starting Admin Interface
2021-03-24 09:11:48.400106 WARNING AppDaemon: ------------------------------------------------------------
2021-03-24 09:11:48.401497 WARNING AppDaemon: Unexpected error in HTTP module
2021-03-24 09:11:48.402793 WARNING AppDaemon: ------------------------------------------------------------
2021-03-24 09:11:48.420900 WARNING AppDaemon: Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/appdaemon/http.py", line 208, in init
self.admin_obj = adadmin.Admin(
TypeError: type object argument after ** must be a mapping, not str
2021-03-24 09:11:48.423402 WARNING AppDaemon: ------------------------------------------------------------
2021-03-24 09:11:48.490118 INFO HASS: Connected to Home Assistant 2021.3.4
2021-03-24 09:11:48.546994 INFO AppDaemon: App 'hello_world' added
2021-03-24 09:11:48.551601 INFO AppDaemon: Found 1 total apps
```

Please report this, with the configuration that causes this, with the AppDaemon project.

Thanks! 👍
